export const MATRICULA_ESTADOS = {
  MATRICULADO: 'MATRICULADO',
  PREINSCRITO : 'PREINSCRITO',
  PENDIENTE: 'PENDIENTE',
  RETIRADO: 'RETIRADO',
  SUSPENDIDO: 'SUSPENDIDO',
  EGRESADO: 'EGRESADO',
  TRASLADADO: 'TRASLADADO',
  ANULADO: 'ANULADO',
} as const;

